my_splitting_app/split_app/auth.py
from flask import Blueprint, redirect, render_template, flash, request, session, url_for
from flask_login import login_required, logout_user, current_user, login_user
from .forms import LoginForm, SignupForm
from .models import db, User
from . import login_manager

auth_bp = Blueprint(
    "auth_bp", __name__, template_folder="templates", static_folder="static"
)


@auth_bp.route("/signup", methods=["GET", "POST"])
def signup():
    """
    User sign-up page.

    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(name=form.name.data, email=form.email.data)
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect(url_for("main_bp.dashboard"))
        flash("A user already exists with that email address.")
    return render_template(
        "signup.html",
        title="Create an Account.",
        form=form,
        template="signup-page",
        body="Sign up for a user account.",
    )


@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    """
    Log-in page for registered users.

    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for("main_bp.dashboard"))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get("next")
            return redirect(next_page or url_for("main_bp.dashboard"))
        flash("Invalid username/password combination")
        return redirect(url_for("auth_bp.login"))
    return render_template(
        "login.html",
        form=form,
        title="Log in.",
        template="login-page",
        body="Log in with your User account.",
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash("You must be logged in to view that page.")
    return redirect(url_for("auth_bp.login"))

my_splitting_app/split_app/routes.py
"""Logged-in page routes."""
from ast import Try
import base64
from pathlib import Path
from tkinter import N
from unicodedata import name
from flask import (
    Blueprint,
    render_template,
    redirect,
    send_file,
    url_for,
    request,
    flash,
    Flask,
    send_from_directory,
)
from .zips import zipper
from .forms import UpdateDetailsForm
from flask_login import current_user, login_required, logout_user
from werkzeug.utils import secure_filename
from zipfile import ZipFile
import os
from .models import db, User
from . import splitter

# Blueprint Configuration
main_bp = Blueprint(
    "main_bp", __name__, template_folder="templates", static_folder="static"
)

ALLOWED_EXTENSIONS = {"csv", "json"}
ALLOWED_IMAGE_EXTENSIONS = {"gif", "jpg", "png", "jpeg"}


@main_bp.route("/")
@main_bp.route("/index")
def index():
    """Logged-in User Dashboard."""
    return render_template(
        "index.html",
        title="Index Page",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/contactUS")
def contactUs():
    """Logged-in User Dashboard."""
    return render_template(
        "contactUs.html",
        title="Contact-Us Page",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/documentation")
def documentation():
    """Logged-in User Dashboard."""
    return render_template(
        "documentation.html",
        title="Contact-Us Page",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/tools")
def tools():
    """Logged-in User Dashboard."""
    return render_template(
        "tools.html",
        title="Contact-Us Page",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/gettingStarted")
def gettingStarted():
    """Logged-in User Dashboard."""
    return render_template(
        "gettingStarted.html",
        title="Contact-Us Page",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/faq")
def faq():
    """Logged-in User Dashboard."""
    return render_template(
        "faq.html",
        title="FAQ Page",
        template="dashboard-template",
        current_user=current_user,
    )

@main_bp.route("/privacy")
def policy():
    """Logged-in User Dashboard."""
    return render_template(
        "policy.html",
        title="FAQ Page",
        template="dashboard-template",
        current_user=current_user,
    )    

@main_bp.route("/terms&conditions")
def terms():
    """Logged-in User Dashboard."""
    return render_template(
        "terms.html",
        title="FAQ Page",
        template="dashboard-template",
        current_user=current_user,
    )

@main_bp.route("/aboutUs")
def aboutUs():
    """Logged-in User Dashboard."""
    return render_template(
        "aboutUs.html",
        title="About-Us",
        template="dashboard-template",
        current_user=current_user,
    )


@main_bp.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    """Logged-in User Dashboard."""
    return render_template(
        "newUserDashboard.html",
        title="User Dashboard",
        template="dashboard-template",
        current_user=current_user,
        body="You are now logged in!",
    )


@main_bp.route("/settings/<name>", methods=["GET"])
@login_required
def settings(name):
    """Logged-in User Dashboard."""

    # Return 404 if path doesn't exist

    # Show directory contents

    return render_template(
        "settings.html",
        title="Settings Dashboard",
        template="dashboard-template",
        current_user=current_user,
        body="You are now logged in!",
    )


@main_bp.route("/storage/<name>", methods=["GET"])
@login_required
def storage(name):
    """Logged-in User Dashboard."""
    BASE_DIR = Path.cwd()/"static"/"uploads"

    # Joining the base and the requested path
    abs_path = os.path.join(BASE_DIR)

    # Return 404 if path doesn't exist
    if not os.path.exists(abs_path):
        return os.abort(404)

    # Check if path is a file and serve
    if os.path.isfile(abs_path):
        return send_file(abs_path)

    # Show directory contents
    files = os.listdir(abs_path)
    xfiles = []
    for file in files:
        newfile = file.split("_")
        if newfile[0] == name:
            xfiles.append(file)

    return render_template(
        "storage.html",
        title="User Dashboard",
        template="dashboard-template",
        current_user=current_user,
        body="You are now logged in!",
        files=xfiles,
    )


def allowed_file(filename):
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


def allowed_image_file(filename):
    return (
        "." in filename
        and filename.rsplit(".", 1)[1].lower() in ALLOWED_IMAGE_EXTENSIONS
    )


@main_bp.route("/settings/<name>", methods=["GET", "POST"])
@login_required
def upload_image_file(name):
    print(request.method, "ududu")
    if request.method == "POST":
        # check if the post request has the file part
        if "file" not in request.files:
            flash("No file part")
            return redirect(url_for("main_bp.dashboard"))
        file = request.files["file"]
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == "":
            flash("No selected file")
            return redirect(url_for("main_bp.dashboard"))
        if file and allowed_image_file(file.filename):
            filename = secure_filename(file.filename)
            filename = filename.split(".")
            file.save(
                os.path.join(
                    Path.cwd()/"static"/"uploads"/"pictures",
                    f"{name}.{filename[-1]}",
                )
            )
            return redirect(f"/settings")
    return "Wrong request method"


@main_bp.route("/uploader/<name>", methods=["GET", "POST"])
@login_required
def upload_file(name):
    print(request.method)
    if request.method == "POST":
        print("kk")
        # check if the post request has the file part
        if "file" not in request.files:
            flash("No file part")
            return redirect(url_for("main_bp.dashboard"))
        file = request.files["file"]
        # If the user does not select a file, the browser submits an
        # empty file without a filename.
        if file.filename == "":
            flash("No selected file")
            return redirect(url_for("main_bp.dashboard"))
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(
                os.path.join(
                    Path.cwd()/"static"/"uploads",
                    filename,
                )
            )
            try:
                limit = int(request.form["amount"])
            except:
                limit = 10000

            savename = filename.split(".")
            splitter.split(
                open(
                    os.path.join(
                        Path.cwd()/"static"/"uploads",
                        filename,
                    ),
                    "r",
                ),
                output_path= Path.cwd()/"static"/"uploads",
                output_name_template=f"{name}_{savename[0]}_",
                row_limit=limit,
                filename=filename,
            )

            nFilename = filename.split(".")
            delete_item(filename, name)
            zipper(nFilename[0], name)
            return redirect(f"/storage/{name}")
    return "Wrong request method"


@main_bp.route("/uploads/<name>")
def download_file(name):
    return send_from_directory(
        Path.cwd()/"static"/"uploads", name
    )


def render_picture(data):
    render_pic = base64.b64encode(data).decode("ascii")
    return render_pic


@main_bp.route("/upload/picture/<email>", methods=["GET", "POST"])
@login_required
def uploadPicture(email):
    if request.method == "POST":
        existing_user = User.query.filter_by(email=email).first()
        if "inputFile" not in request.files:
            flash("No file part", "error")
            redirect((f"/settings/{existing_user.name}"))
        file = request.files["inputFile"]
        if file.filename == "":
            flash("No selected file")
            redirect((f"/settings/{existing_user.name}"))
        data = file.read()
        render_file = render_picture(data)
        text = email
        existing_user.data = data
        existing_user.text = text
        existing_user.rendered_data = render_file
        db.session.commit()
        return redirect((f"/settings/{existing_user.name}"))


@main_bp.route("/updateprofile/<email>", methods=["GET", "POST"])
@login_required
def updateProfile(email):
    if request.method == "POST":
        name = request.form["name"]
        email = request.form["email"]
        newPassword = request.form["newPassword"]
        oldPassword = request.form["oldPassword"]
        confirmPassword = request.form["confirmPassword"]
        existing_user = User.query.filter_by(email=email).first()
        if name.rstrip != "":
            existing_user.name = name
        if email.rstrip != "":
            existing_user.email = email
        if newPassword != "" and existing_user.check_password(oldPassword):
            if newPassword == confirmPassword:
                existing_user.set_password(newPassword)
        db.session.commit()
        flash("Update Successful")
        return redirect((f"/settings/{existing_user.name}"))


@main_bp.route("/delete_item/<filename>/<name>", methods=["GET", "POST"])
@login_required
def delete_item(filename, name):
    try:

        file_path = os.path.join(
            Path.cwd()/"static"/"uploads",
            filename,
        )
        os.remove(file_path)

    except Exception as error:

my_splitting_app/split_app/templates/documentation.html
<!DOCTYPE html>
<html lang="en">
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='styles/documentation.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='styles/general.css') }}"
    />
    <script src="{{url_for('static', filename='javascripts/dark.js')}}" defer></script>

    <title>Documentation Page</title>
  </head>
  <body>
    <header>
      <div class="header_wrapper">
        <div class="logo flex_c">
          <div class="logo__img flex_c">
            <img src="{{ url_for('static', filename = 'Images/Ellipse 13.png') }}" class="blue" alt="logo icon" />
            <img src="{{ url_for('static', filename = 'Images/Ellipse 14.png') }}" class="light" alt="logo icon" />
          </div>
          <p>
            Chun<span class="keet">keet</span>
          </p>
        </div>
        <div class="desktop__navigations flex_c">
          <nav class="nav__bar">
            <ul class="flex_c">
              <li>
                <a href="{{ url_for('main_bp.index') }}" >Home</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.contactUs') }}">Contact Us</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.aboutUs') }}">About Us</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.documentation') }}" class="active">Documentation</a>
              </li>
            </ul>
          </nav>
          <div class="toggle">
            <div class="dark_mode">
              <small>Dark</small>
              <img src="{{ url_for('static', filename = 'Images/dark-icon.png') }}" alt="dark icon" />
            </div>
            <div class="light_mode">
              <small>Light</small>
              <img src=" {{ url_for('static', filename = 'Images/light-Icon.png') }} " alt="light icon" />
            </div>
          </div>
          <div class="buttons flex_c">
            <a href="{{ url_for('auth_bp.login') }}" class="btn unfilled">Sign In</a>
            <a href="{{ url_for('auth_bp.signup') }}" class="btn filled">Sign Up</a>
          </div>
        </div>
      </div>
      <!--  <div class="mobile__navigations">
            <nav class="nav__bar">
                <ul>
                    <li>Home</li>
                    <li>Contact Us</li>
                    <li>About Us</li>
                </ul>
            </nav>
            <div class="buttons">
                <a href="#" class="btn unfilled"></a >
                <a href="#" class="btn filled"></a >
            </div>
          </div>  -->
    </header>
    <main class="container">
      <section class="left_side">
        <nav>
          <ul class="nav__items">
            <li class="nav__item active">
              <a href="{{ url_for('main_bp.documentation') }}">Introduction</a>
            </li>
            <li class="nav__item">
              <a href="{{ url_for('main_bp.gettingStarted') }}">Getting Started</a>
            </li>
            <li class="nav__item">
              <a href="{{ url_for('main_bp.tools') }}">How the tools work</a>
            </li>
            <li class="nav__item ">
              <a href="{{ url_for('main_bp.faq') }}">FAQs</a>
            </li>
          </ul>
        </nav>
      </section>

      <section class="right_side">
        <div id="introduction">
          <div class="part">
            <h1>Introduction</h1>
            <p>
              Chunkeet is a platform that accepts large CSV and JSON files and
              breaks them into smaller bits while maintaining the right format.
              The platform allows authenticated users, to upload their large
              files, chunk it into bits and download to their local device. Team
              44 has been able to solve most issues related to splitting of CSV
              and JSON files. Issues like; chunked files inaccuracy, data
              incompletion and system errors etc.
            </p>
          </div>
          <div class="part">
            <h2>What is a CSV File</h2>
            <p>
              A CSV file is information seperated using commas, It’s a way to
              exchange structured information, like the contents of a
              spreadsheet. Due to its simplicity, CSV can be used by virtually
              anyone who examines data in spreadsheets and tables. We offer
              splitting and conversion of CSV files. This tool allows you to
              split large CSV files into smaller files based on your
              specicification. There is no limit of files to split. The only
              constraints are the browser, your computer and the optimized code
              of this tool.
            </p>
          </div>
          <div class="part">
            <h2>what is a JSON File</h2>
            <p>
              JSON is an open standard file format for sharing Data that uses
              human-readable text to store and transmit data. It is a general
              data format used with different applications, including web
              applications. It is a lightweight format for storing and
              transporting data. Web Developers use JSON to transmit data from
              the server to the web browser and from =the web browser back to
              the server.
            </p>
          </div>
          <div class="part">
            <h2>What makes our platform different</h2>
            <ol>
              <li>Splitting of CSV and JSON.</li>
              <li>Conversion of CSV to JSON files and vice versa</li>
              <li>
                Providing Users a website with great User Interface and User
                Experience.
              </li>
              <li>A save to download later option.</li>
              <li>
                Ad free website, many websites that are doing what we are doing
                hardly provide an ad free website which is always frustrating to
                the Users.
              </li>
              <li>
                Registered Users get to have his/her own dashboard so as to
                enjoy other benefits on our websites.
              </li>
              <li>
                We included a dark mode for users that prefers the dark mode to
                light mode.
              </li>
            </ol>
          </div>
        </div>
      </section>
    </main>
    <!-- Footer -->
    <footer>
      <div class="footer__wrapper">
        <div class="left">
          <div class="left__footer">
            <div class="footer__logo logo flex_c">
              <div class="logo__img">
                <img
                  src=" {{ url_for('static', filename='Images/Ellipse 13.png') }} "
                  class="blue"
                  alt="logo icon"
                />
                <img
                  src="{{ url_for('static', filename='Images/Ellipse 14.png') }} "
                  class="light"
                  alt="logo icon"
                />
              </div>
              <p class="footer__chun">Chun<span class="keet">keet</span></p>
            </div>
            <p class="chunk">
              Chunkeet application we aim at accepting large file and breaking
              them into bits while maintaining the right format.
            </p>
          </div>
          <div class="socials">
            <ul>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/google-icon.png') }} "
                  alt="google icon"
                />
              </li>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/facebook-icon.png') }}"
                  alt="facebook icon"
                  class="facebook"
                />
              </li>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/twitter-icon.png') }}"
                  alt="twitter icon"
                />
              </li>
            </ul>
          </div>
        </div>
        <div class="right flex_c">
          <div class="useful__links">
            <h3>Useful Links</h3>
            <ul>
              <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.index') }}">Home</a>
            </li>
            <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.aboutUs') }}">About Us</a>
            </li>
            <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.contactUs') }}">Contact Us</a>
            </li>
            </ul>
          </div>
          <div class="help">
            <h3>Help</h3>
            <ul>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.documentation') }}">Documentation</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.faq') }}">FAQs</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.terms') }}">Terms and Conditions</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.policy') }}">Privacy Policy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="copyright">&COPY; Chunkeet</div>
    </footer>
  </body>
</html>

my_splitting_app/split_app/templates/gettingStarted.html
<!DOCTYPE html>
<html lang="en">
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='styles/documentation.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='styles/general.css') }}"
    />
    <script src="{{url_for('static', filename='javascripts/dark.js')}}" defer></script>

    <title>Documentation Page</title>
  </head>
  <body>
    <header>
      <div class="header_wrapper">
        <div class="logo flex_c">
          <div class="logo__img flex_c">
            <img src="{{ url_for('static', filename = 'Images/Ellipse 13.png') }}" class="blue" alt="logo icon" />
            <img src="{{ url_for('static', filename = 'Images/Ellipse 14.png') }}" class="light" alt="logo icon" />
          </div>
          <p>
            Chun<span class="keet">keet</span>
          </p>
        </div>
        <div class="desktop__navigations flex_c">
          <nav class="nav__bar">
            <ul class="flex_c">
              <li>
                <a href="{{ url_for('main_bp.index') }}" >Home</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.contactUs') }}">Contact Us</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.aboutUs') }}">About Us</a>
              </li>
              <li>
                <a href="{{ url_for('main_bp.documentation') }}" class="active">Documentation</a>
              </li>
            </ul>
          </nav>
          <div class="toggle">
            <div class="dark_mode">
              <small>Dark</small>
              <img src="{{ url_for('static', filename = 'Images/dark-icon.png') }}" alt="dark icon" />
            </div>
            <div class="light_mode">
              <small>Light</small>
              <img src=" {{ url_for('static', filename = 'Images/light-Icon.png') }} " alt="light icon" />
            </div>
          </div>
          <div class="buttons flex_c">
            <a href="{{ url_for('auth_bp.login') }}" class="btn unfilled">Sign In</a>
            <a href="{{ url_for('auth_bp.signup') }}" class="btn filled">Sign Up</a>
          </div>
        </div>
      </div>
      <!--  <div class="mobile__navigations">
            <nav class="nav__bar">
                <ul>
                    <li>Home</li>
                    <li>Contact Us</li>
                    <li>About Us</li>
                </ul>
            </nav>
            <div class="buttons">
                <a href="#" class="btn unfilled"></a >
                <a href="#" class="btn filled"></a >
            </div>
          </div>  -->
    </header>
    <main class="container">
      <section class="left_side">
        <nav>
          <ul class="nav__items">
            <li class="nav__item">
              <a class="white" href="{{ url_for('main_bp.documentation') }}">Introduction</a>
            </li>
            <li class="nav__item active">
              <a class="white" href="{{ url_for('main_bp.gettingStarted') }}"
                >Getting Started</a
              >
            </li>
            <li class="nav__item">
              <a class="white" href="{{ url_for('main_bp.tools') }}">How the tools work</a>
            </li>
            <li class="nav__item active">
              <a class="white" href="{{ url_for('main_bp.faq') }}">FAQs</a>
            </li>
          </ul>
        </nav>
      </section>

      <section class="right_side">
        <div id="getting__started">
          <div class="part">
            <h1>Getting Started</h1>
            <ol>
              <li>Go to www.chunkeet.com</li>
              <li>Register or Sign Up</li>
              <li>Go to your Dashboard</li>
              <li>Drag and Drop file or Browse file</li>
              <li>Input chunking Parameters</li>
              <li>Chunk file</li>
              <li>Finish chunking</li>
              <li>Save chunked file to Storage</li>
              <li>Download chunked file to User local Storage</li>
              <li>Save temporarily in Draft.</li>
            </ol>
          </div>
        </div>
      </section>
    </main>
    <!-- Footer -->
    <footer>
      <div class="footer__wrapper">
        <div class="left">
          <div class="left__footer">
            <div class="footer__logo logo flex_c">
              <div class="logo__img">
                <img
                  src=" {{ url_for('static', filename='Images/Ellipse 13.png') }} "
                  class="blue"
                  alt="logo icon"
                />
                <img
                  src="{{ url_for('static', filename='Images/Ellipse 14.png') }} "
                  class="light"
                  alt="logo icon"
                />
              </div>
              <p class="footer__chun">Chun<span class="keet">keet</span></p>
            </div>
            <p class="chunk">
              Chunkeet application we aim at accepting large file and breaking
              them into bits while maintaining the right format.
            </p>
          </div>
          <div class="socials">
            <ul>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/google-icon.png') }} "
                  alt="google icon"
                />
              </li>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/facebook-icon.png') }}"
                  alt="facebook icon"
                  class="facebook"
                />
              </li>
              <li>
                <img
                  src="{{ url_for('static', filename='Images/twitter-icon.png') }}"
                  alt="twitter icon"
                />
              </li>
            </ul>
          </div>
        </div>
        <div class="right flex_c">
          <div class="useful__links">
            <h3>Useful Links</h3>
            <ul>
              <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.index') }}">Home</a>
            </li>
            <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.aboutUs') }}">About Us</a>
            </li>
            <li>
              <img
                src="{{ url_for('static', filename='/Images/arrow.png') }}"
                alt="arrow icon"
              />
              <a href="{{ url_for('main_bp.contactUs') }}">Contact Us</a>
            </li>
            </ul>
          </div>
          <div class="help">
            <h3>Help</h3>
            <ul>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.documentation') }}">Documentation</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.faq') }}">FAQs</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.terms') }}">Terms and Conditions</a>
              </li>
              <li>
                <img src="{{ url_for('static', filename='/Images/arrow.png') }}" alt="arrow icon" />
                <a href="{{ url_for('main_bp.policy') }}">Privacy Policy</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div class="copyright">&COPY; Chunkeet</div>
    </footer>
  </body>
</html>